name: Validate Wiki configuration

on:
  pull_request:
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Compose configuration
        run: docker compose --env-file .env.example config --quiet
      - name: Validate shell script
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './'
